package com.tarun1sisodia.catparallax.engine

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Color
import android.graphics.LinearGradient
import android.graphics.Paint
import android.graphics.Path
import android.graphics.RectF
import android.graphics.Shader
import org.json.JSONArray
import org.json.JSONObject

/**
 * Loads the wallpaper scene:
 *  - assets/cat/custom/ + custom.json + PNG cels, if the user supplied the
 *    minimum required set (tail, body, eyes_open, eyes_closed);
 *  - otherwise the built-in code-drawn cat from assets/cat/default_cat.json
 *    (generated by tools/cat_design.py — the single source of truth).
 *
 * The returned CatScene is pre-fitted to the given surface size, including a
 * ready-to-use full-surface gradient Paint for the sky layer.
 */
object SceneLoader {

    private const val DEFAULT_SCENE = "cat/default_cat.json"
    private const val CUSTOM_DIR = "cat/custom"

    fun load(context: Context, surfaceW: Int, surfaceH: Int): CatScene {
        val raw = loadCustom(context) ?: loadDefault(context)
        return fit(raw, surfaceW, surfaceH)
    }

    // ------------------------------------------------------------------ raw --

    /** Parsed scene before fitting: geometry in design units + sky gradient stops. */
    private class RawScene(
        val designW: Float,
        val designH: Float,
        val catPivotX: Float,
        val catPivotY: Float,
        val layers: List<ParallaxLayer>,
        val gradientY0: Float,
        val gradientY1: Float,
        val gradientColors: IntArray,
        val gradientPositions: FloatArray,
        val skyTopColor: Int
    )

    // ------------------------------------------------------------------ fit --

    private fun fit(raw: RawScene, surfaceW: Int, surfaceH: Int): CatScene {
        // Cover-fit: the design always covers the whole surface (content near
        // design-space edges may crop on tall screens, which is why all
        // full-bleed layers extend well past the edges).
        val scale = maxOf(surfaceW / raw.designW, surfaceH / raw.designH)
        val offX = (surfaceW - raw.designW * scale) / 2f
        val offY = (surfaceH - raw.designH * scale) / 2f

        val paint = Paint()
        paint.shader = LinearGradient(
            0f, raw.gradientY0 * scale + offY,
            0f, raw.gradientY1 * scale + offY,
            raw.gradientColors, raw.gradientPositions, Shader.TileMode.CLAMP
        )

        return CatScene(
            designWidth = raw.designW,
            designHeight = raw.designH,
            catPivotX = raw.catPivotX,
            catPivotY = raw.catPivotY,
            layers = raw.layers.filter { it.kind != LayerKind.GRADIENT },
            toggleableLayerIds = raw.layers.filter { it.toggleable }.map { it.id },
            scale = scale,
            offsetX = offX,
            offsetY = offY,
            skyTopColor = raw.skyTopColor,
            gradientPaint = paint
        )
    }

    // -------------------------------------------------------- default scene --

    private fun loadDefault(context: Context): RawScene {
        val json = context.assets.open(DEFAULT_SCENE).bufferedReader().use { it.readText() }
        val root = JSONObject(json)
        val dw = root.optDouble("designWidth", 1000.0).toFloat()
        val dh = root.optDouble("designHeight", 1600.0).toFloat()
        val catPivot = root.optJSONArray("catPivot")
        val catPivotX = catPivot?.optDouble(0)?.toFloat() ?: dw / 2f
        val catPivotY = catPivot?.optDouble(1)?.toFloat() ?: dh

        val arr = root.getJSONArray("layers")
        val layers = ArrayList<ParallaxLayer>(arr.length())
        var gradientY0 = 0f
        var gradientY1 = dh
        var gradientColors = intArrayOf(Color.BLACK, Color.BLACK)
        var gradientPositions = floatArrayOf(0f, 1f)
        var skyTopColor = Color.BLACK

        for (i in 0 until arr.length()) {
            val l = arr.optJSONObject(i) ?: continue
            val id = l.optString("id", "layer$i")

            if (l.optString("kind") == "gradient") {
                gradientY0 = l.optDouble("y0", 0.0).toFloat()
                gradientY1 = l.optDouble("y1", dh.toDouble()).toFloat()
                val stops = l.optJSONArray("stops")
                if (stops != null && stops.length() > 0) {
                    gradientColors = IntArray(stops.length())
                    gradientPositions = FloatArray(stops.length())
                    for (s in 0 until stops.length()) {
                        val stop = stops.optJSONArray(s)
                        gradientColors[s] = parseColor(stop.optString(0))
                        gradientPositions[s] = stop.optDouble(1).toFloat()
                    }
                    skyTopColor = gradientColors[0]
                }
                // gradient layers are consumed by CatScene.gradientPaint
                layers.add(
                    ParallaxLayer(
                        id = id, kind = LayerKind.GRADIENT, depth = 0f,
                        role = LayerRole.NONE, toggleable = false,
                        pivotX = dw / 2f, pivotY = dh / 2f,
                        paths = null, variants = null, defaultVariant = null,
                        shapes = null, bitmap = null, bitmapRect = null
                    )
                )
                continue
            }

            val kind = when (l.optString("kind")) {
                "shapes" -> LayerKind.SHAPES
                "bitmap" -> LayerKind.BITMAP
                else -> LayerKind.PATHS
            }
            val role = when (l.optString("role")) {
                "body" -> LayerRole.BODY
                "tail" -> LayerRole.TAIL
                "ear_l" -> LayerRole.EAR_LEFT
                "ear_r" -> LayerRole.EAR_RIGHT
                "eyes" -> LayerRole.EYES
                else -> LayerRole.NONE
            }
            val pivotArr = l.optJSONArray("pivot")
            val pivotX = pivotArr?.optDouble(0)?.toFloat() ?: dw / 2f
            val pivotY = pivotArr?.optDouble(1)?.toFloat() ?: dh / 2f

            var paths: List<DrawablePath>? = null
            var variants: Map<String, List<DrawablePath>>? = null
            var defaultVariant: String? = null
            if (l.has("variants")) {
                val vObj = l.getJSONObject("variants")
                val map = HashMap<String, List<DrawablePath>>()
                for (key in vObj.keys()) {
                    map[key] = parsePaths(vObj.getJSONArray(key))
                }
                variants = map
                defaultVariant = l.optString("defaultVariant", "open")
            } else if (l.has("paths")) {
                paths = parsePaths(l.getJSONArray("paths"))
            }

            var shapes: List<ShapeCmd>? = null
            if (l.has("shapes")) {
                val sArr = l.getJSONArray("shapes")
                val list = ArrayList<ShapeCmd>(sArr.length())
                for (s in 0 until sArr.length()) {
                    val sh = sArr.optJSONObject(s) ?: continue
                    val type = when (sh.optString("c")) {
                        "circle" -> ShapeCmd.CIRCLE
                        "ellipse" -> ShapeCmd.ELLIPSE
                        else -> ShapeCmd.SPARKLE
                    }
                    list.add(
                        ShapeCmd(
                            type = type,
                            x = sh.optDouble("x").toFloat(),
                            y = sh.optDouble("y").toFloat(),
                            r = sh.optDouble("r").toFloat(),
                            rx = sh.optDouble("rx").toFloat(),
                            ry = sh.optDouble("ry").toFloat(),
                            fill = parseColor(sh.optString("fill", "#FFFFFF")),
                            alpha = sh.optDouble("alpha", 1.0).toFloat()
                        )
                    )
                }
                shapes = list
            }

            layers.add(
                ParallaxLayer(
                    id = id,
                    kind = kind,
                    depth = l.optDouble("depth", 0.5).toFloat(),
                    role = role,
                    toggleable = l.optBoolean("toggleable", false),
                    pivotX = pivotX,
                    pivotY = pivotY,
                    paths = paths,
                    variants = variants,
                    defaultVariant = defaultVariant,
                    shapes = shapes,
                    bitmap = null,
                    bitmapRect = null
                )
            )
        }

        return RawScene(
            dw, dh, catPivotX, catPivotY, layers,
            gradientY0, gradientY1, gradientColors, gradientPositions, skyTopColor
        )
    }

    private fun parsePaths(arr: JSONArray): List<DrawablePath> {
        val list = ArrayList<DrawablePath>(arr.length())
        for (i in 0 until arr.length()) {
            val p = arr.optJSONObject(i) ?: continue
            val d = p.optString("d", "")
            val fillHex = p.optString("fill", "")
            val strokeHex = p.optString("stroke", "")
            list.add(
                DrawablePath(
                    path = PathParser.parse(d),
                    fill = if (fillHex.isNotEmpty()) parseColor(fillHex) else 0,
                    hasFill = fillHex.isNotEmpty(),
                    stroke = if (strokeHex.isNotEmpty()) parseColor(strokeHex) else 0,
                    hasStroke = strokeHex.isNotEmpty(),
                    strokeWidth = p.optDouble("sw", 4.0).toFloat(),
                    alpha = p.optDouble("alpha", 1.0).toFloat()
                )
            )
        }
        return list
    }

    private fun parseColor(hex: String): Int = try {
        Color.parseColor(hex)
    } catch (e: IllegalArgumentException) {
        Color.WHITE
    }

    // --------------------------------------------------------- custom scene --

    /**
     * Loads user-supplied PNG cels. Returns null unless the minimum required
     * set exists (tail, body, eyes_open, eyes_closed) — a half-filled folder
     * never produces a broken scene.
     *
     * Conventions (see assets/cat/custom/README.md):
     *  - cat cels are square PNGs mapped to the design band (0, topOffset, 1000, topOffset+1000)
     *  - bg.png / fg.png cover-map the full design rect (uniform scale)
     *  - eye variants are separate files: eyes_open / eyes_closed / eyes_wide
     */
    private fun loadCustom(context: Context): RawScene? {
        val names = try {
            context.assets.list(CUSTOM_DIR)?.toList() ?: emptyList()
        } catch (e: Exception) {
            return null
        }
        fun has(f: String) = names.contains(f)
        if (!has("tail.png") || !has("body.png") ||
            !has("eyes_open.png") || !has("eyes_closed.png")
        ) return null

        val dw = 1000f
        val dh = 1600f

        var depthBg = 0.15f
        var depthBody = 0.72f
        var depthEars = 0.75f
        var depthEyes = 0.82f
        var depthTail = 0.86f
        var depthFg = 1.0f
        var tailPivotX = 600f
        var tailPivotY = 1150f
        var topOffset = 300f
        if (has("custom.json")) {
            try {
                val cfg = JSONObject(
                    context.assets.open("$CUSTOM_DIR/custom.json")
                        .bufferedReader().use { it.readText() }
                )
                val depth = cfg.optJSONObject("depth")
                if (depth != null) {
                    depthBg = depth.optDouble("bg", depthBg.toDouble()).toFloat()
                    depthBody = depth.optDouble("body", depthBody.toDouble()).toFloat()
                    depthEars = depth.optDouble("ears", depthEars.toDouble()).toFloat()
                    depthEyes = depth.optDouble("eyes", depthEyes.toDouble()).toFloat()
                    depthTail = depth.optDouble("tail", depthTail.toDouble()).toFloat()
                    depthFg = depth.optDouble("fg", depthFg.toDouble()).toFloat()
                }
                val tp = cfg.optJSONArray("tailPivot")
                if (tp != null) {
                    tailPivotX = tp.optDouble(0).toFloat()
                    tailPivotY = tp.optDouble(1).toFloat()
                }
                topOffset = cfg.optDouble("topOffset", topOffset.toDouble()).toFloat()
            } catch (e: Exception) {
                // malformed custom.json -> keep defaults
            }
        }

        fun decode(name: String): Bitmap? = try {
            context.assets.open("$CUSTOM_DIR/$name").use {
                BitmapFactory.decodeStream(it)
            }
        } catch (e: Exception) {
            null
        }

        val layers = ArrayList<ParallaxLayer>()
        val catBand = { RectF(0f, topOffset, dw, topOffset + dw) }

        fun celLayer(
            id: String, file: String, depth: Float, role: LayerRole,
            pivotX: Float, pivotY: Float, toggleable: Boolean = false
        ): ParallaxLayer? {
            val bmp = decode(file) ?: return null
            return ParallaxLayer(
                id = id, kind = LayerKind.BITMAP, depth = depth, role = role,
                toggleable = toggleable, pivotX = pivotX, pivotY = pivotY,
                paths = null, variants = null, defaultVariant = null,
                shapes = null, bitmap = bmp, bitmapRect = catBand()
            )
        }

        fun fullBleedLayer(id: String, file: String, depth: Float): ParallaxLayer? {
            val bmp = decode(file) ?: return null
            return ParallaxLayer(
                id = id, kind = LayerKind.BITMAP, depth = depth, role = LayerRole.NONE,
                toggleable = true, pivotX = dw / 2f, pivotY = dh / 2f,
                paths = null, variants = null, defaultVariant = null,
                shapes = null, bitmap = bmp, bitmapRect = RectF(-300f, 0f, dw + 300f, dh)
            )
        }

        // Custom scenes don't carry a gradient; keep the default dusk sky.
        val gradientColors = intArrayOf(
            parseColor("#141034"), parseColor("#4A2C63"),
            parseColor("#C4597B"), parseColor("#FFB37A")
        )
        val gradientPositions = floatArrayOf(0f, 0.42f, 0.62f, 0.75f)
        layers.add(
            ParallaxLayer(
                id = "bg", kind = LayerKind.GRADIENT, depth = 0f,
                role = LayerRole.NONE, toggleable = false,
                pivotX = dw / 2f, pivotY = dh / 2f,
                paths = null, variants = null, defaultVariant = null,
                shapes = null, bitmap = null, bitmapRect = null
            )
        )

        fullBleedLayer("bg", "bg.png", depthBg)?.let { layers.add(it) }

        // Required cels: if any of them fails to decode, fall back to the
        // built-in cat instead of crashing the wallpaper engine.
        val bodyLayer = celLayer("body", "body.png", depthBody, LayerRole.BODY,
            pivotX = dw / 2f, pivotY = topOffset + 958f)
        val tailLayer = celLayer("tail", "tail.png", depthTail, LayerRole.TAIL,
            pivotX = tailPivotX, pivotY = tailPivotY, toggleable = true)
        val eyesOpenLayer = celLayer("eyes_open", "eyes_open.png", depthEyes, LayerRole.EYES,
            pivotX = dw / 2f, pivotY = dh / 2f)
        val eyesClosedLayer = celLayer("eyes_closed", "eyes_closed.png", depthEyes, LayerRole.EYES,
            pivotX = dw / 2f, pivotY = dh / 2f)
        if (bodyLayer == null || tailLayer == null ||
            eyesOpenLayer == null || eyesClosedLayer == null
        ) return null

        layers.add(bodyLayer)
        celLayer("ear_l", "ear_left.png", depthEars, LayerRole.EAR_LEFT,
            pivotX = 404f, pivotY = topOffset + 316f)?.let { layers.add(it) }
        celLayer("ear_r", "ear_right.png", depthEars, LayerRole.EAR_RIGHT,
            pivotX = 596f, pivotY = topOffset + 316f)?.let { layers.add(it) }
        layers.add(eyesOpenLayer)
        layers.add(eyesClosedLayer)
        celLayer("eyes_wide", "eyes_wide.png", depthEyes, LayerRole.EYES,
            pivotX = dw / 2f, pivotY = dh / 2f)?.let { layers.add(it) }
        layers.add(tailLayer)
        fullBleedLayer("fg", "fg.png", depthFg)?.let { layers.add(it) }

        return RawScene(
            dw, dh, dw / 2f, topOffset + 958f, layers,
            0f, dh, gradientColors, gradientPositions, gradientColors[0]
        )
    }
}

/**
 * Minimal SVG-ish path parser. Supports absolute M / L / C / Q / Z — exactly
 * the vocabulary emitted by tools/cat_design.py.
 */
object PathParser {

    fun parse(d: String): Path {
        val path = Path()
        val toks = d.replace(",", " ").split(" ").filter { it.isNotEmpty() }
        var i = 0
        val n = toks.size
        while (i < n) {
            when (toks[i]) {
                "M" -> {
                    if (i + 2 < n) {
                        path.moveTo(toks[i + 1].toFloat(), toks[i + 2].toFloat())
                        i += 3
                    } else i = n
                }
                "L" -> {
                    if (i + 2 < n) {
                        path.lineTo(toks[i + 1].toFloat(), toks[i + 2].toFloat())
                        i += 3
                    } else i = n
                }
                "C" -> {
                    if (i + 6 < n) {
                        path.cubicTo(
                            toks[i + 1].toFloat(), toks[i + 2].toFloat(),
                            toks[i + 3].toFloat(), toks[i + 4].toFloat(),
                            toks[i + 5].toFloat(), toks[i + 6].toFloat()
                        )
                        i += 7
                    } else i = n
                }
                "Q" -> {
                    if (i + 4 < n) {
                        path.quadTo(
                            toks[i + 1].toFloat(), toks[i + 2].toFloat(),
                            toks[i + 3].toFloat(), toks[i + 4].toFloat()
                        )
                        i += 5
                    } else i = n
                }
                "Z" -> {
                    path.close()
                    i += 1
                }
                else -> i += 1
            }
        }
        return path
    }
}
